<!DOCTYPE html>
<html>
    <head>
        <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">-->
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Phalcon PHP Framework</title>
         <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <base href="/PCD/"/>
    {% block library %}
        {{ stylesheet_link('css/cssPlantilla.css') }}
        {{ javascript_include('js/jquery-2.1.4.min.js') }}
        {{ stylesheet_link('css/cssProfile.css') }}
        {{ javascript_include('js/general.js') }}
        {{ javascript_include('js/profile.js') }}
        
    {% endblock %}
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <script src="js/canvasengine-1.3.2.all.min.js" type="text/javascript"></script>
        <script src="js/jquery-1.11.3.min.js" type="text/javascript"></script>
     
       
       
        <script src="js/hammer.min.js" type="text/javascript"></script>
        <script src="js/chicken.js" type="text/javascript"></script>
        <script src="js/alien.js" type="text/javascript"></script>
     
    </head>
    <body>
        {{ content() }}
    </body>
</html>
