<header></header>
<a href="index/logout"><div id="logoutbuttom">LOGOUT</div></a>
<div id="contenedorPuntuaciones">
    
    <br/>
    <a href="jugar"><div id="playButtom">JUGAR</div></a>
    
    <br/>
    <div>
        <span class="tituloPuntuacion">Mis puntuaciones:</span>
        <div id="contenedorPersonal" class="contenedores"></div>
    </div>
    <div>
        <span class="tituloPuntuacion">Puntuaciones globales:</span>
        <div id="contenedorGlobal" class="contenedores"></div>
    </div>
</div>



<script>
    var userName={{ userName | json_encode }};
    var personalProfile = new PersonalProfile();
    personalProfile.init();
</script>
<!--<footer></footer>-->