<header></header>
<div id="contenedorPuntuaciones">
    <br/>
    <a><div id="playButtom">JUGAR</div></a>
    <br/>
    <div>
        <span class="tituloPuntuacion">Mis puntuaciones:</span>
        <div id="contenedorPersonal" class="contenedores"></div>
    </div>
    <div>
        <span class="tituloPuntuacion">Puntuaciones globales:</span>
        <div id="contenedorGlobal" class="contenedores"></div>
    </div>
</div>



<script>
    var personalProfile = new PersonalProfile();
    personalProfile.init();
</script>
<!--<footer></footer>-->